// flow-typed signature: 6b6f30cbd786f679aff9051aff25544c
// flow-typed version: <<STUB>>/@oneblink/types_vgithub:oneblink/types/flow_v0.138.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@oneblink/types'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@oneblink/types' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@oneblink/types/flow-typed/api' {
  declare module.exports: any;
}

declare module '@oneblink/types/flow-typed/cdn' {
  declare module.exports: any;
}

declare module '@oneblink/types/flow-typed/console' {
  declare module.exports: any;
}

declare module '@oneblink/types/flow-typed/email-templates' {
  declare module.exports: any;
}

declare module '@oneblink/types/flow-typed/environments' {
  declare module.exports: any;
}

declare module '@oneblink/types/flow-typed/form-statistics' {
  declare module.exports: any;
}

declare module '@oneblink/types/flow-typed/forms-app-user-subscriptions' {
  declare module.exports: any;
}

declare module '@oneblink/types/flow-typed/forms-apps' {
  declare module.exports: any;
}

declare module '@oneblink/types/flow-typed/forms' {
  declare module.exports: any;
}

declare module '@oneblink/types/flow-typed/geoscape/address-details' {
  declare module.exports: any;
}

declare module '@oneblink/types/flow-typed/geoscape/addresses' {
  declare module.exports: any;
}

declare module '@oneblink/types/flow-typed/geoscape' {
  declare module.exports: any;
}

declare module '@oneblink/types/flow-typed/integrations' {
  declare module.exports: any;
}

declare module '@oneblink/types/flow-typed/keys' {
  declare module.exports: any;
}

declare module '@oneblink/types/flow-typed/organisations' {
  declare module.exports: any;
}

declare module '@oneblink/types/flow-typed/submission-events' {
  declare module.exports: any;
}

declare module '@oneblink/types/flow-typed/submissions' {
  declare module.exports: any;
}

declare module '@oneblink/types/flow-typed/team-members' {
  declare module.exports: any;
}

// Filename aliases
declare module '@oneblink/types/flow-typed/api.js' {
  declare module.exports: $Exports<'@oneblink/types/flow-typed/api'>;
}
declare module '@oneblink/types/flow-typed/cdn.js' {
  declare module.exports: $Exports<'@oneblink/types/flow-typed/cdn'>;
}
declare module '@oneblink/types/flow-typed/console.js' {
  declare module.exports: $Exports<'@oneblink/types/flow-typed/console'>;
}
declare module '@oneblink/types/flow-typed/email-templates.js' {
  declare module.exports: $Exports<'@oneblink/types/flow-typed/email-templates'>;
}
declare module '@oneblink/types/flow-typed/environments.js' {
  declare module.exports: $Exports<'@oneblink/types/flow-typed/environments'>;
}
declare module '@oneblink/types/flow-typed/form-statistics.js' {
  declare module.exports: $Exports<'@oneblink/types/flow-typed/form-statistics'>;
}
declare module '@oneblink/types/flow-typed/forms-app-user-subscriptions.js' {
  declare module.exports: $Exports<'@oneblink/types/flow-typed/forms-app-user-subscriptions'>;
}
declare module '@oneblink/types/flow-typed/forms-apps.js' {
  declare module.exports: $Exports<'@oneblink/types/flow-typed/forms-apps'>;
}
declare module '@oneblink/types/flow-typed/forms.js' {
  declare module.exports: $Exports<'@oneblink/types/flow-typed/forms'>;
}
declare module '@oneblink/types/flow-typed/geoscape/address-details.js' {
  declare module.exports: $Exports<'@oneblink/types/flow-typed/geoscape/address-details'>;
}
declare module '@oneblink/types/flow-typed/geoscape/addresses.js' {
  declare module.exports: $Exports<'@oneblink/types/flow-typed/geoscape/addresses'>;
}
declare module '@oneblink/types/flow-typed/geoscape/index' {
  declare module.exports: $Exports<'@oneblink/types/flow-typed/geoscape'>;
}
declare module '@oneblink/types/flow-typed/geoscape/index.js' {
  declare module.exports: $Exports<'@oneblink/types/flow-typed/geoscape'>;
}
declare module '@oneblink/types/flow-typed/integrations.js' {
  declare module.exports: $Exports<'@oneblink/types/flow-typed/integrations'>;
}
declare module '@oneblink/types/flow-typed/keys.js' {
  declare module.exports: $Exports<'@oneblink/types/flow-typed/keys'>;
}
declare module '@oneblink/types/flow-typed/organisations.js' {
  declare module.exports: $Exports<'@oneblink/types/flow-typed/organisations'>;
}
declare module '@oneblink/types/flow-typed/submission-events.js' {
  declare module.exports: $Exports<'@oneblink/types/flow-typed/submission-events'>;
}
declare module '@oneblink/types/flow-typed/submissions.js' {
  declare module.exports: $Exports<'@oneblink/types/flow-typed/submissions'>;
}
declare module '@oneblink/types/flow-typed/team-members.js' {
  declare module.exports: $Exports<'@oneblink/types/flow-typed/team-members'>;
}
