// flow-typed signature: bcc71e7fb7dcad608f9d67d6cbe84f27
// flow-typed version: <<STUB>>/@jokeyrhyme/pify-fs_v1.0.1/flow_v0.119.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@jokeyrhyme/pify-fs'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@jokeyrhyme/pify-fs' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module '@jokeyrhyme/pify-fs/index' {
  declare module.exports: $Exports<'@jokeyrhyme/pify-fs'>;
}
declare module '@jokeyrhyme/pify-fs/index.js' {
  declare module.exports: $Exports<'@jokeyrhyme/pify-fs'>;
}
