// flow-typed signature: befa80bb0027993d3b0922e04d13a8b3
// flow-typed version: <<STUB>>/@hapi/boom_v^9.1.0/flow_v0.138.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@hapi/boom'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@hapi/boom' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@hapi/boom/lib' {
  declare module.exports: any;
}

// Filename aliases
declare module '@hapi/boom/lib/index' {
  declare module.exports: $Exports<'@hapi/boom/lib'>;
}
declare module '@hapi/boom/lib/index.js' {
  declare module.exports: $Exports<'@hapi/boom/lib'>;
}
