// flow-typed signature: adb270de63689f0ad256309d848dc9d9
// flow-typed version: <<STUB>>/argv-one_v1.0.1/flow_v0.119.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'argv-one'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'argv-one' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'argv-one/bin' {
  declare module.exports: any;
}

// Filename aliases
declare module 'argv-one/bin/index' {
  declare module.exports: $Exports<'argv-one/bin'>;
}
declare module 'argv-one/bin/index.js' {
  declare module.exports: $Exports<'argv-one/bin'>;
}
declare module 'argv-one/index' {
  declare module.exports: $Exports<'argv-one'>;
}
declare module 'argv-one/index.js' {
  declare module.exports: $Exports<'argv-one'>;
}
