// flow-typed signature: 92e8d20d8f015b8b314f38646888d94d
// flow-typed version: <<STUB>>/boom_v7.3.0/flow_v0.119.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'boom'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'boom' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'boom/lib' {
  declare module.exports: any;
}

// Filename aliases
declare module 'boom/lib/index' {
  declare module.exports: $Exports<'boom/lib'>;
}
declare module 'boom/lib/index.js' {
  declare module.exports: $Exports<'boom/lib'>;
}
