// flow-typed signature: 2c1cad12cef0b7b60cffa1c05fccae4f
// flow-typed version: <<STUB>>/cli-table2_v^0.2.0/flow_v0.138.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'cli-table2'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'cli-table2' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'cli-table2/examples/basic-usage-examples' {
  declare module.exports: any;
}

declare module 'cli-table2/examples/col-and-row-span-examples' {
  declare module.exports: any;
}

declare module 'cli-table2/gulpfile' {
  declare module.exports: any;
}

declare module 'cli-table2/lib/print-example' {
  declare module.exports: any;
}

declare module 'cli-table2/src/cell' {
  declare module.exports: any;
}

declare module 'cli-table2/src/layout-manager' {
  declare module.exports: any;
}

declare module 'cli-table2/src/table' {
  declare module.exports: any;
}

declare module 'cli-table2/src/utils' {
  declare module.exports: any;
}

declare module 'cli-table2/test/cell-test' {
  declare module.exports: any;
}

declare module 'cli-table2/test/example-tests' {
  declare module.exports: any;
}

declare module 'cli-table2/test/layout-manager-test' {
  declare module.exports: any;
}

declare module 'cli-table2/test/original-cli-table-index-tests' {
  declare module.exports: any;
}

declare module 'cli-table2/test/original-cli-table-newlines-test' {
  declare module.exports: any;
}

declare module 'cli-table2/test/table-layout-test' {
  declare module.exports: any;
}

declare module 'cli-table2/test/table-test' {
  declare module.exports: any;
}

declare module 'cli-table2/test/utils-test' {
  declare module.exports: any;
}

declare module 'cli-table2/test/verify-legacy-compatibility-test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'cli-table2/examples/basic-usage-examples.js' {
  declare module.exports: $Exports<'cli-table2/examples/basic-usage-examples'>;
}
declare module 'cli-table2/examples/col-and-row-span-examples.js' {
  declare module.exports: $Exports<'cli-table2/examples/col-and-row-span-examples'>;
}
declare module 'cli-table2/gulpfile.js' {
  declare module.exports: $Exports<'cli-table2/gulpfile'>;
}
declare module 'cli-table2/index' {
  declare module.exports: $Exports<'cli-table2'>;
}
declare module 'cli-table2/index.js' {
  declare module.exports: $Exports<'cli-table2'>;
}
declare module 'cli-table2/lib/print-example.js' {
  declare module.exports: $Exports<'cli-table2/lib/print-example'>;
}
declare module 'cli-table2/src/cell.js' {
  declare module.exports: $Exports<'cli-table2/src/cell'>;
}
declare module 'cli-table2/src/layout-manager.js' {
  declare module.exports: $Exports<'cli-table2/src/layout-manager'>;
}
declare module 'cli-table2/src/table.js' {
  declare module.exports: $Exports<'cli-table2/src/table'>;
}
declare module 'cli-table2/src/utils.js' {
  declare module.exports: $Exports<'cli-table2/src/utils'>;
}
declare module 'cli-table2/test/cell-test.js' {
  declare module.exports: $Exports<'cli-table2/test/cell-test'>;
}
declare module 'cli-table2/test/example-tests.js' {
  declare module.exports: $Exports<'cli-table2/test/example-tests'>;
}
declare module 'cli-table2/test/layout-manager-test.js' {
  declare module.exports: $Exports<'cli-table2/test/layout-manager-test'>;
}
declare module 'cli-table2/test/original-cli-table-index-tests.js' {
  declare module.exports: $Exports<'cli-table2/test/original-cli-table-index-tests'>;
}
declare module 'cli-table2/test/original-cli-table-newlines-test.js' {
  declare module.exports: $Exports<'cli-table2/test/original-cli-table-newlines-test'>;
}
declare module 'cli-table2/test/table-layout-test.js' {
  declare module.exports: $Exports<'cli-table2/test/table-layout-test'>;
}
declare module 'cli-table2/test/table-test.js' {
  declare module.exports: $Exports<'cli-table2/test/table-test'>;
}
declare module 'cli-table2/test/utils-test.js' {
  declare module.exports: $Exports<'cli-table2/test/utils-test'>;
}
declare module 'cli-table2/test/verify-legacy-compatibility-test.js' {
  declare module.exports: $Exports<'cli-table2/test/verify-legacy-compatibility-test'>;
}
