// flow-typed signature: ebef26ea36df6b57576e65cadf2211e8
// flow-typed version: <<STUB>>/cli-table3_v^0.6.0/flow_v0.138.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'cli-table3'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'cli-table3' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'cli-table3/src/cell' {
  declare module.exports: any;
}

declare module 'cli-table3/src/layout-manager' {
  declare module.exports: any;
}

declare module 'cli-table3/src/table' {
  declare module.exports: any;
}

declare module 'cli-table3/src/utils' {
  declare module.exports: any;
}

// Filename aliases
declare module 'cli-table3/index' {
  declare module.exports: $Exports<'cli-table3'>;
}
declare module 'cli-table3/index.js' {
  declare module.exports: $Exports<'cli-table3'>;
}
declare module 'cli-table3/src/cell.js' {
  declare module.exports: $Exports<'cli-table3/src/cell'>;
}
declare module 'cli-table3/src/layout-manager.js' {
  declare module.exports: $Exports<'cli-table3/src/layout-manager'>;
}
declare module 'cli-table3/src/table.js' {
  declare module.exports: $Exports<'cli-table3/src/table'>;
}
declare module 'cli-table3/src/utils.js' {
  declare module.exports: $Exports<'cli-table3/src/utils'>;
}
