// flow-typed signature: 0b742303ae794aa7fb4795ec3c72fdec
// flow-typed version: <<STUB>>/good-console_v7.1.0/flow_v0.119.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'good-console'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'good-console' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'good-console/lib' {
  declare module.exports: any;
}

declare module 'good-console/test/fixture/streams' {
  declare module.exports: any;
}

declare module 'good-console/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'good-console/lib/index' {
  declare module.exports: $Exports<'good-console/lib'>;
}
declare module 'good-console/lib/index.js' {
  declare module.exports: $Exports<'good-console/lib'>;
}
declare module 'good-console/test/fixture/streams.js' {
  declare module.exports: $Exports<'good-console/test/fixture/streams'>;
}
declare module 'good-console/test/index' {
  declare module.exports: $Exports<'good-console/test'>;
}
declare module 'good-console/test/index.js' {
  declare module.exports: $Exports<'good-console/test'>;
}
