// flow-typed signature: b0ac3e8b204dd227a6bd1d2c60dd8235
// flow-typed version: <<STUB>>/load-json-file_v6.2.0/flow_v0.119.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'load-json-file'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'load-json-file' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'load-json-file/index' {
  declare module.exports: $Exports<'load-json-file'>;
}
declare module 'load-json-file/index.js' {
  declare module.exports: $Exports<'load-json-file'>;
}
