// flow-typed signature: 2dc74b2be4e93deaf93f49ac4f9200a7
// flow-typed version: <<STUB>>/meow_v6.0.1/flow_v0.119.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'meow'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'meow' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'meow/index' {
  declare module.exports: $Exports<'meow'>;
}
declare module 'meow/index.js' {
  declare module.exports: $Exports<'meow'>;
}
