// flow-typed signature: b4d70b292c71c78f3c7a79d4c0b14432
// flow-typed version: <<STUB>>/npm-bin-ava-tester_v^1.1.0/flow_v0.138.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'npm-bin-ava-tester'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'npm-bin-ava-tester' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'npm-bin-ava-tester/lib' {
  declare module.exports: any;
}

// Filename aliases
declare module 'npm-bin-ava-tester/lib/index' {
  declare module.exports: $Exports<'npm-bin-ava-tester/lib'>;
}
declare module 'npm-bin-ava-tester/lib/index.js' {
  declare module.exports: $Exports<'npm-bin-ava-tester/lib'>;
}
