// flow-typed signature: eb472027bcc74a77e6ecaee38cbcf47a
// flow-typed version: <<STUB>>/object-merge_v2.5.1/flow_v0.119.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'object-merge'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'object-merge' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'object-merge/browser/jasmine/jasmine-html' {
  declare module.exports: any;
}

declare module 'object-merge/browser/jasmine/jasmine' {
  declare module.exports: any;
}

declare module 'object-merge/browser/object-merge_web' {
  declare module.exports: any;
}

declare module 'object-merge/browser/tests/object-merge.test' {
  declare module.exports: any;
}

declare module 'object-merge/dev/browserify' {
  declare module.exports: any;
}

declare module 'object-merge/dev/browserMain' {
  declare module.exports: any;
}

declare module 'object-merge/specs/object-merge.Spec' {
  declare module.exports: any;
}

declare module 'object-merge/src/object-merge' {
  declare module.exports: any;
}

// Filename aliases
declare module 'object-merge/browser/jasmine/jasmine-html.js' {
  declare module.exports: $Exports<'object-merge/browser/jasmine/jasmine-html'>;
}
declare module 'object-merge/browser/jasmine/jasmine.js' {
  declare module.exports: $Exports<'object-merge/browser/jasmine/jasmine'>;
}
declare module 'object-merge/browser/object-merge_web.js' {
  declare module.exports: $Exports<'object-merge/browser/object-merge_web'>;
}
declare module 'object-merge/browser/tests/object-merge.test.js' {
  declare module.exports: $Exports<'object-merge/browser/tests/object-merge.test'>;
}
declare module 'object-merge/dev/browserify.js' {
  declare module.exports: $Exports<'object-merge/dev/browserify'>;
}
declare module 'object-merge/dev/browserMain.js' {
  declare module.exports: $Exports<'object-merge/dev/browserMain'>;
}
declare module 'object-merge/specs/object-merge.Spec.js' {
  declare module.exports: $Exports<'object-merge/specs/object-merge.Spec'>;
}
declare module 'object-merge/src/object-merge.js' {
  declare module.exports: $Exports<'object-merge/src/object-merge'>;
}
