// flow-typed signature: 618b8ce9c2b9d1efe5583317d314f8fd
// flow-typed version: <<STUB>>/open_v^7.4.1/flow_v0.138.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'open'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'open' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'open/index' {
  declare module.exports: $Exports<'open'>;
}
declare module 'open/index.js' {
  declare module.exports: $Exports<'open'>;
}
