// flow-typed signature: 5d34fbf39da55658bfcfc66e48f87a3e
// flow-typed version: <<STUB>>/package-engines-notifier_v1.1.0/flow_v0.119.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'package-engines-notifier'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'package-engines-notifier' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'package-engines-notifier/index' {
  declare module.exports: $Exports<'package-engines-notifier'>;
}
declare module 'package-engines-notifier/index.js' {
  declare module.exports: $Exports<'package-engines-notifier'>;
}
