// flow-typed signature: 31ca12968285d0b77b7e30ca60715920
// flow-typed version: <<STUB>>/parse-package-name_v0.1.0/flow_v0.119.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'parse-package-name'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'parse-package-name' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'parse-package-name/index' {
  declare module.exports: $Exports<'parse-package-name'>;
}
declare module 'parse-package-name/index.js' {
  declare module.exports: $Exports<'parse-package-name'>;
}
