// flow-typed signature: 5fa2f2b70c6e841e1a29c1fc7680f657
// flow-typed version: <<STUB>>/pify_v4.0.1/flow_v0.119.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'pify'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'pify' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'pify/index' {
  declare module.exports: $Exports<'pify'>;
}
declare module 'pify/index.js' {
  declare module.exports: $Exports<'pify'>;
}
