// flow-typed signature: e0ace963e0ca97d04f91275f2641fb2d
// flow-typed version: <<STUB>>/proxyquire_v^2.1.3/flow_v0.138.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'proxyquire'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'proxyquire' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'proxyquire/examples/api/api-test' {
  declare module.exports: any;
}

declare module 'proxyquire/examples/api/samples/bar' {
  declare module.exports: any;
}

declare module 'proxyquire/examples/api/samples/foo' {
  declare module.exports: any;
}

declare module 'proxyquire/examples/api/samples/stats' {
  declare module.exports: any;
}

declare module 'proxyquire/examples/async/foo-tests' {
  declare module.exports: any;
}

declare module 'proxyquire/examples/async/foo' {
  declare module.exports: any;
}

declare module 'proxyquire/examples/example-utils' {
  declare module.exports: any;
}

declare module 'proxyquire/examples/simple/foo.inlineoverride.test' {
  declare module.exports: any;
}

declare module 'proxyquire/examples/simple/foo' {
  declare module.exports: any;
}

declare module 'proxyquire/examples/simple/foo.test' {
  declare module.exports: any;
}

declare module 'proxyquire/examples/sinon/foo-tests' {
  declare module.exports: any;
}

declare module 'proxyquire/examples/sinon/foo' {
  declare module.exports: any;
}

declare module 'proxyquire/lib/is' {
  declare module.exports: any;
}

declare module 'proxyquire/lib/proxyquire-error' {
  declare module.exports: any;
}

declare module 'proxyquire/lib/proxyquire' {
  declare module.exports: any;
}

declare module 'proxyquire/test/proxyquire-api' {
  declare module.exports: any;
}

declare module 'proxyquire/test/proxyquire-argumentvalidation' {
  declare module.exports: any;
}

declare module 'proxyquire/test/proxyquire-cache' {
  declare module.exports: any;
}

declare module 'proxyquire/test/proxyquire-compat' {
  declare module.exports: any;
}

declare module 'proxyquire/test/proxyquire-extensions' {
  declare module.exports: any;
}

declare module 'proxyquire/test/proxyquire-global' {
  declare module.exports: any;
}

declare module 'proxyquire/test/proxyquire-independence' {
  declare module.exports: any;
}

declare module 'proxyquire/test/proxyquire-non-object' {
  declare module.exports: any;
}

declare module 'proxyquire/test/proxyquire-notexisting' {
  declare module.exports: any;
}

declare module 'proxyquire/test/proxyquire-relative-paths' {
  declare module.exports: any;
}

declare module 'proxyquire/test/proxyquire-remove' {
  declare module.exports: any;
}

declare module 'proxyquire/test/proxyquire-sub-dependencies' {
  declare module.exports: any;
}

declare module 'proxyquire/test/proxyquire' {
  declare module.exports: any;
}

declare module 'proxyquire/test/samples/bar' {
  declare module.exports: any;
}

declare module 'proxyquire/test/samples/boof' {
  declare module.exports: any;
}

declare module 'proxyquire/test/samples/cache/bar' {
  declare module.exports: any;
}

declare module 'proxyquire/test/samples/cache/foo' {
  declare module.exports: any;
}

declare module 'proxyquire/test/samples/extensions' {
  declare module.exports: any;
}

declare module 'proxyquire/test/samples/foo-singleton' {
  declare module.exports: any;
}

declare module 'proxyquire/test/samples/foo' {
  declare module.exports: any;
}

declare module 'proxyquire/test/samples/fooarray' {
  declare module.exports: any;
}

declare module 'proxyquire/test/samples/foobool' {
  declare module.exports: any;
}

declare module 'proxyquire/test/samples/foonum' {
  declare module.exports: any;
}

declare module 'proxyquire/test/samples/global/bar' {
  declare module.exports: any;
}

declare module 'proxyquire/test/samples/global/baz' {
  declare module.exports: any;
}

declare module 'proxyquire/test/samples/global/foo-deferred' {
  declare module.exports: any;
}

declare module 'proxyquire/test/samples/global/foo' {
  declare module.exports: any;
}

declare module 'proxyquire/test/samples/no-call-thru-test' {
  declare module.exports: any;
}

declare module 'proxyquire/test/samples/no-call-thru-test/required' {
  declare module.exports: any;
}

declare module 'proxyquire/test/samples/notexisting/foo-relative' {
  declare module.exports: any;
}

declare module 'proxyquire/test/samples/notexisting/foo' {
  declare module.exports: any;
}

declare module 'proxyquire/test/samples/relative-paths/a' {
  declare module.exports: any;
}

declare module 'proxyquire/test/samples/relative-paths/a/util' {
  declare module.exports: any;
}

declare module 'proxyquire/test/samples/relative-paths/b' {
  declare module.exports: any;
}

declare module 'proxyquire/test/samples/relative-paths/b/util' {
  declare module.exports: any;
}

declare module 'proxyquire/test/samples/stats' {
  declare module.exports: any;
}

declare module 'proxyquire/test/samples/sub-dependencies/bar' {
  declare module.exports: any;
}

declare module 'proxyquire/test/samples/sub-dependencies/baz' {
  declare module.exports: any;
}

declare module 'proxyquire/test/samples/sub-dependencies/foo' {
  declare module.exports: any;
}

// Filename aliases
declare module 'proxyquire/examples/api/api-test.js' {
  declare module.exports: $Exports<'proxyquire/examples/api/api-test'>;
}
declare module 'proxyquire/examples/api/samples/bar.js' {
  declare module.exports: $Exports<'proxyquire/examples/api/samples/bar'>;
}
declare module 'proxyquire/examples/api/samples/foo.js' {
  declare module.exports: $Exports<'proxyquire/examples/api/samples/foo'>;
}
declare module 'proxyquire/examples/api/samples/stats.js' {
  declare module.exports: $Exports<'proxyquire/examples/api/samples/stats'>;
}
declare module 'proxyquire/examples/async/foo-tests.js' {
  declare module.exports: $Exports<'proxyquire/examples/async/foo-tests'>;
}
declare module 'proxyquire/examples/async/foo.js' {
  declare module.exports: $Exports<'proxyquire/examples/async/foo'>;
}
declare module 'proxyquire/examples/example-utils.js' {
  declare module.exports: $Exports<'proxyquire/examples/example-utils'>;
}
declare module 'proxyquire/examples/simple/foo.inlineoverride.test.js' {
  declare module.exports: $Exports<'proxyquire/examples/simple/foo.inlineoverride.test'>;
}
declare module 'proxyquire/examples/simple/foo.js' {
  declare module.exports: $Exports<'proxyquire/examples/simple/foo'>;
}
declare module 'proxyquire/examples/simple/foo.test.js' {
  declare module.exports: $Exports<'proxyquire/examples/simple/foo.test'>;
}
declare module 'proxyquire/examples/sinon/foo-tests.js' {
  declare module.exports: $Exports<'proxyquire/examples/sinon/foo-tests'>;
}
declare module 'proxyquire/examples/sinon/foo.js' {
  declare module.exports: $Exports<'proxyquire/examples/sinon/foo'>;
}
declare module 'proxyquire/index' {
  declare module.exports: $Exports<'proxyquire'>;
}
declare module 'proxyquire/index.js' {
  declare module.exports: $Exports<'proxyquire'>;
}
declare module 'proxyquire/lib/is.js' {
  declare module.exports: $Exports<'proxyquire/lib/is'>;
}
declare module 'proxyquire/lib/proxyquire-error.js' {
  declare module.exports: $Exports<'proxyquire/lib/proxyquire-error'>;
}
declare module 'proxyquire/lib/proxyquire.js' {
  declare module.exports: $Exports<'proxyquire/lib/proxyquire'>;
}
declare module 'proxyquire/test/proxyquire-api.js' {
  declare module.exports: $Exports<'proxyquire/test/proxyquire-api'>;
}
declare module 'proxyquire/test/proxyquire-argumentvalidation.js' {
  declare module.exports: $Exports<'proxyquire/test/proxyquire-argumentvalidation'>;
}
declare module 'proxyquire/test/proxyquire-cache.js' {
  declare module.exports: $Exports<'proxyquire/test/proxyquire-cache'>;
}
declare module 'proxyquire/test/proxyquire-compat.js' {
  declare module.exports: $Exports<'proxyquire/test/proxyquire-compat'>;
}
declare module 'proxyquire/test/proxyquire-extensions.js' {
  declare module.exports: $Exports<'proxyquire/test/proxyquire-extensions'>;
}
declare module 'proxyquire/test/proxyquire-global.js' {
  declare module.exports: $Exports<'proxyquire/test/proxyquire-global'>;
}
declare module 'proxyquire/test/proxyquire-independence.js' {
  declare module.exports: $Exports<'proxyquire/test/proxyquire-independence'>;
}
declare module 'proxyquire/test/proxyquire-non-object.js' {
  declare module.exports: $Exports<'proxyquire/test/proxyquire-non-object'>;
}
declare module 'proxyquire/test/proxyquire-notexisting.js' {
  declare module.exports: $Exports<'proxyquire/test/proxyquire-notexisting'>;
}
declare module 'proxyquire/test/proxyquire-relative-paths.js' {
  declare module.exports: $Exports<'proxyquire/test/proxyquire-relative-paths'>;
}
declare module 'proxyquire/test/proxyquire-remove.js' {
  declare module.exports: $Exports<'proxyquire/test/proxyquire-remove'>;
}
declare module 'proxyquire/test/proxyquire-sub-dependencies.js' {
  declare module.exports: $Exports<'proxyquire/test/proxyquire-sub-dependencies'>;
}
declare module 'proxyquire/test/proxyquire.js' {
  declare module.exports: $Exports<'proxyquire/test/proxyquire'>;
}
declare module 'proxyquire/test/samples/bar.js' {
  declare module.exports: $Exports<'proxyquire/test/samples/bar'>;
}
declare module 'proxyquire/test/samples/boof.js' {
  declare module.exports: $Exports<'proxyquire/test/samples/boof'>;
}
declare module 'proxyquire/test/samples/cache/bar.js' {
  declare module.exports: $Exports<'proxyquire/test/samples/cache/bar'>;
}
declare module 'proxyquire/test/samples/cache/foo.js' {
  declare module.exports: $Exports<'proxyquire/test/samples/cache/foo'>;
}
declare module 'proxyquire/test/samples/extensions.js' {
  declare module.exports: $Exports<'proxyquire/test/samples/extensions'>;
}
declare module 'proxyquire/test/samples/foo-singleton.js' {
  declare module.exports: $Exports<'proxyquire/test/samples/foo-singleton'>;
}
declare module 'proxyquire/test/samples/foo.js' {
  declare module.exports: $Exports<'proxyquire/test/samples/foo'>;
}
declare module 'proxyquire/test/samples/fooarray.js' {
  declare module.exports: $Exports<'proxyquire/test/samples/fooarray'>;
}
declare module 'proxyquire/test/samples/foobool.js' {
  declare module.exports: $Exports<'proxyquire/test/samples/foobool'>;
}
declare module 'proxyquire/test/samples/foonum.js' {
  declare module.exports: $Exports<'proxyquire/test/samples/foonum'>;
}
declare module 'proxyquire/test/samples/global/bar.js' {
  declare module.exports: $Exports<'proxyquire/test/samples/global/bar'>;
}
declare module 'proxyquire/test/samples/global/baz.js' {
  declare module.exports: $Exports<'proxyquire/test/samples/global/baz'>;
}
declare module 'proxyquire/test/samples/global/foo-deferred.js' {
  declare module.exports: $Exports<'proxyquire/test/samples/global/foo-deferred'>;
}
declare module 'proxyquire/test/samples/global/foo.js' {
  declare module.exports: $Exports<'proxyquire/test/samples/global/foo'>;
}
declare module 'proxyquire/test/samples/no-call-thru-test/index' {
  declare module.exports: $Exports<'proxyquire/test/samples/no-call-thru-test'>;
}
declare module 'proxyquire/test/samples/no-call-thru-test/index.js' {
  declare module.exports: $Exports<'proxyquire/test/samples/no-call-thru-test'>;
}
declare module 'proxyquire/test/samples/no-call-thru-test/required.js' {
  declare module.exports: $Exports<'proxyquire/test/samples/no-call-thru-test/required'>;
}
declare module 'proxyquire/test/samples/notexisting/foo-relative.js' {
  declare module.exports: $Exports<'proxyquire/test/samples/notexisting/foo-relative'>;
}
declare module 'proxyquire/test/samples/notexisting/foo.js' {
  declare module.exports: $Exports<'proxyquire/test/samples/notexisting/foo'>;
}
declare module 'proxyquire/test/samples/relative-paths/a/index' {
  declare module.exports: $Exports<'proxyquire/test/samples/relative-paths/a'>;
}
declare module 'proxyquire/test/samples/relative-paths/a/index.js' {
  declare module.exports: $Exports<'proxyquire/test/samples/relative-paths/a'>;
}
declare module 'proxyquire/test/samples/relative-paths/a/util.js' {
  declare module.exports: $Exports<'proxyquire/test/samples/relative-paths/a/util'>;
}
declare module 'proxyquire/test/samples/relative-paths/b/index' {
  declare module.exports: $Exports<'proxyquire/test/samples/relative-paths/b'>;
}
declare module 'proxyquire/test/samples/relative-paths/b/index.js' {
  declare module.exports: $Exports<'proxyquire/test/samples/relative-paths/b'>;
}
declare module 'proxyquire/test/samples/relative-paths/b/util.js' {
  declare module.exports: $Exports<'proxyquire/test/samples/relative-paths/b/util'>;
}
declare module 'proxyquire/test/samples/stats.js' {
  declare module.exports: $Exports<'proxyquire/test/samples/stats'>;
}
declare module 'proxyquire/test/samples/sub-dependencies/bar.js' {
  declare module.exports: $Exports<'proxyquire/test/samples/sub-dependencies/bar'>;
}
declare module 'proxyquire/test/samples/sub-dependencies/baz.js' {
  declare module.exports: $Exports<'proxyquire/test/samples/sub-dependencies/baz'>;
}
declare module 'proxyquire/test/samples/sub-dependencies/foo.js' {
  declare module.exports: $Exports<'proxyquire/test/samples/sub-dependencies/foo'>;
}
