// flow-typed signature: cca719f38a6234366c8b701f578e67bd
// flow-typed version: <<STUB>>/recursive-copy_v2.0.10/flow_v0.119.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'recursive-copy'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'recursive-copy' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'recursive-copy/lib/copy' {
  declare module.exports: any;
}

// Filename aliases
declare module 'recursive-copy/index' {
  declare module.exports: $Exports<'recursive-copy'>;
}
declare module 'recursive-copy/index.js' {
  declare module.exports: $Exports<'recursive-copy'>;
}
declare module 'recursive-copy/lib/copy.js' {
  declare module.exports: $Exports<'recursive-copy/lib/copy'>;
}
