// flow-typed signature: ca07d9b165ab92374fcbaed983dce06c
// flow-typed version: <<STUB>>/temp_v^0.9.4/flow_v0.138.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'temp'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'temp' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'temp/lib/temp' {
  declare module.exports: any;
}

// Filename aliases
declare module 'temp/lib/temp.js' {
  declare module.exports: $Exports<'temp/lib/temp'>;
}
