// flow-typed signature: 6d86a5dc2cf627c8b81f9c1ac9d748fe
// flow-typed version: <<STUB>>/uniloc_v0.3.0/flow_v0.119.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'uniloc'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'uniloc' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'uniloc/uniloc' {
  declare module.exports: any;
}

// Filename aliases
declare module 'uniloc/uniloc.js' {
  declare module.exports: $Exports<'uniloc/uniloc'>;
}
