// flow-typed signature: 9c4c22614ac1cac4b351bb4c0b2b087a
// flow-typed version: <<STUB>>/write-json-file_v4.2.1/flow_v0.119.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'write-json-file'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'write-json-file' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'write-json-file/index' {
  declare module.exports: $Exports<'write-json-file'>;
}
declare module 'write-json-file/index.js' {
  declare module.exports: $Exports<'write-json-file'>;
}
