// flow-typed signature: a09d3efb7fc1fce3d665b0fe4b0857b1
// flow-typed version: <<STUB>>/@blinkmobile/aws-s3_v^2.2.0/flow_v0.138.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@blinkmobile/aws-s3'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@blinkmobile/aws-s3' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@blinkmobile/aws-s3/lib/delete-objects' {
  declare module.exports: any;
}

declare module '@blinkmobile/aws-s3/lib/list-objects' {
  declare module.exports: any;
}

declare module '@blinkmobile/aws-s3/lib/maps' {
  declare module.exports: any;
}

declare module '@blinkmobile/aws-s3/lib/upload-object' {
  declare module.exports: any;
}

declare module '@blinkmobile/aws-s3/lib/upload' {
  declare module.exports: any;
}

declare module '@blinkmobile/aws-s3/lib/utils/bucket-path-prefix-helper' {
  declare module.exports: any;
}

declare module '@blinkmobile/aws-s3/lib/utils/fs-map-child' {
  declare module.exports: any;
}

declare module '@blinkmobile/aws-s3/lib/utils/glob' {
  declare module.exports: any;
}

declare module '@blinkmobile/aws-s3/lib/utils/ignore' {
  declare module.exports: any;
}

declare module '@blinkmobile/aws-s3/lib/utils/md5' {
  declare module.exports: any;
}

declare module '@blinkmobile/aws-s3/lib/utils/mime' {
  declare module.exports: any;
}

// Filename aliases
declare module '@blinkmobile/aws-s3/index' {
  declare module.exports: $Exports<'@blinkmobile/aws-s3'>;
}
declare module '@blinkmobile/aws-s3/index.js' {
  declare module.exports: $Exports<'@blinkmobile/aws-s3'>;
}
declare module '@blinkmobile/aws-s3/lib/delete-objects.js' {
  declare module.exports: $Exports<'@blinkmobile/aws-s3/lib/delete-objects'>;
}
declare module '@blinkmobile/aws-s3/lib/list-objects.js' {
  declare module.exports: $Exports<'@blinkmobile/aws-s3/lib/list-objects'>;
}
declare module '@blinkmobile/aws-s3/lib/maps.js' {
  declare module.exports: $Exports<'@blinkmobile/aws-s3/lib/maps'>;
}
declare module '@blinkmobile/aws-s3/lib/upload-object.js' {
  declare module.exports: $Exports<'@blinkmobile/aws-s3/lib/upload-object'>;
}
declare module '@blinkmobile/aws-s3/lib/upload.js' {
  declare module.exports: $Exports<'@blinkmobile/aws-s3/lib/upload'>;
}
declare module '@blinkmobile/aws-s3/lib/utils/bucket-path-prefix-helper.js' {
  declare module.exports: $Exports<'@blinkmobile/aws-s3/lib/utils/bucket-path-prefix-helper'>;
}
declare module '@blinkmobile/aws-s3/lib/utils/fs-map-child.js' {
  declare module.exports: $Exports<'@blinkmobile/aws-s3/lib/utils/fs-map-child'>;
}
declare module '@blinkmobile/aws-s3/lib/utils/glob.js' {
  declare module.exports: $Exports<'@blinkmobile/aws-s3/lib/utils/glob'>;
}
declare module '@blinkmobile/aws-s3/lib/utils/ignore.js' {
  declare module.exports: $Exports<'@blinkmobile/aws-s3/lib/utils/ignore'>;
}
declare module '@blinkmobile/aws-s3/lib/utils/md5.js' {
  declare module.exports: $Exports<'@blinkmobile/aws-s3/lib/utils/md5'>;
}
declare module '@blinkmobile/aws-s3/lib/utils/mime.js' {
  declare module.exports: $Exports<'@blinkmobile/aws-s3/lib/utils/mime'>;
}
