// flow-typed signature: 0e2ca95d9de01d9f59199b1cef562055
// flow-typed version: <<STUB>>/@blinkmobile/blinkmrc_v2.0.0/flow_v0.119.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@blinkmobile/blinkmrc'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@blinkmobile/blinkmrc' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@blinkmobile/blinkmrc/lib/config' {
  declare module.exports: any;
}

declare module '@blinkmobile/blinkmrc/lib/project-config' {
  declare module.exports: any;
}

declare module '@blinkmobile/blinkmrc/lib/user-config' {
  declare module.exports: any;
}

// Filename aliases
declare module '@blinkmobile/blinkmrc/index' {
  declare module.exports: $Exports<'@blinkmobile/blinkmrc'>;
}
declare module '@blinkmobile/blinkmrc/index.js' {
  declare module.exports: $Exports<'@blinkmobile/blinkmrc'>;
}
declare module '@blinkmobile/blinkmrc/lib/config.js' {
  declare module.exports: $Exports<'@blinkmobile/blinkmrc/lib/config'>;
}
declare module '@blinkmobile/blinkmrc/lib/project-config.js' {
  declare module.exports: $Exports<'@blinkmobile/blinkmrc/lib/project-config'>;
}
declare module '@blinkmobile/blinkmrc/lib/user-config.js' {
  declare module.exports: $Exports<'@blinkmobile/blinkmrc/lib/user-config'>;
}
