// flow-typed signature: f07e7769e0e3d240a2e4e1591a7b50cb
// flow-typed version: <<STUB>>/@blinkmobile/bm-identity_v5.1.0-beta.1/flow_v0.119.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@blinkmobile/bm-identity'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@blinkmobile/bm-identity' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@blinkmobile/bm-identity/lib/common/login' {
  declare module.exports: any;
}

declare module '@blinkmobile/bm-identity/lib/common/logout' {
  declare module.exports: any;
}

declare module '@blinkmobile/bm-identity/lib/constants' {
  declare module.exports: any;
}

declare module '@blinkmobile/bm-identity/lib/login-providers/browser' {
  declare module.exports: any;
}

declare module '@blinkmobile/bm-identity/lib/login-providers/login-provider-base' {
  declare module.exports: any;
}

declare module '@blinkmobile/bm-identity/lib/login-providers/username' {
  declare module.exports: any;
}

declare module '@blinkmobile/bm-identity/lib/utils/get-access-token' {
  declare module.exports: any;
}

declare module '@blinkmobile/bm-identity/lib/utils/get-jwt' {
  declare module.exports: any;
}

declare module '@blinkmobile/bm-identity/lib/utils/get-refresh-token' {
  declare module.exports: any;
}

declare module '@blinkmobile/bm-identity/lib/utils/get-tenant-data' {
  declare module.exports: any;
}

declare module '@blinkmobile/bm-identity/lib/utils/user-config' {
  declare module.exports: any;
}

declare module '@blinkmobile/bm-identity/lib/utils/verify-jwt' {
  declare module.exports: any;
}

declare module '@blinkmobile/bm-identity/test/common/login' {
  declare module.exports: any;
}

declare module '@blinkmobile/bm-identity/test/common/logout' {
  declare module.exports: any;
}

declare module '@blinkmobile/bm-identity/test/helpers/base-64-url' {
  declare module.exports: any;
}

declare module '@blinkmobile/bm-identity/test/helpers/inquirer' {
  declare module.exports: any;
}

declare module '@blinkmobile/bm-identity/test/helpers/jsonwebtoken' {
  declare module.exports: any;
}

declare module '@blinkmobile/bm-identity/test/helpers/login-provider-base' {
  declare module.exports: any;
}

declare module '@blinkmobile/bm-identity/test/helpers/login-provider' {
  declare module.exports: any;
}

declare module '@blinkmobile/bm-identity/test/helpers/profile' {
  declare module.exports: any;
}

declare module '@blinkmobile/bm-identity/test/helpers/request' {
  declare module.exports: any;
}

declare module '@blinkmobile/bm-identity/test/helpers/user-config' {
  declare module.exports: any;
}

declare module '@blinkmobile/bm-identity/test/login-providers/browser' {
  declare module.exports: any;
}

declare module '@blinkmobile/bm-identity/test/login-providers/login-provider-base' {
  declare module.exports: any;
}

declare module '@blinkmobile/bm-identity/test/login-providers/username' {
  declare module.exports: any;
}

declare module '@blinkmobile/bm-identity/test/utils/verify-jwt' {
  declare module.exports: any;
}

// Filename aliases
declare module '@blinkmobile/bm-identity/index' {
  declare module.exports: $Exports<'@blinkmobile/bm-identity'>;
}
declare module '@blinkmobile/bm-identity/index.js' {
  declare module.exports: $Exports<'@blinkmobile/bm-identity'>;
}
declare module '@blinkmobile/bm-identity/lib/common/login.js' {
  declare module.exports: $Exports<'@blinkmobile/bm-identity/lib/common/login'>;
}
declare module '@blinkmobile/bm-identity/lib/common/logout.js' {
  declare module.exports: $Exports<'@blinkmobile/bm-identity/lib/common/logout'>;
}
declare module '@blinkmobile/bm-identity/lib/constants.js' {
  declare module.exports: $Exports<'@blinkmobile/bm-identity/lib/constants'>;
}
declare module '@blinkmobile/bm-identity/lib/login-providers/browser.js' {
  declare module.exports: $Exports<'@blinkmobile/bm-identity/lib/login-providers/browser'>;
}
declare module '@blinkmobile/bm-identity/lib/login-providers/login-provider-base.js' {
  declare module.exports: $Exports<'@blinkmobile/bm-identity/lib/login-providers/login-provider-base'>;
}
declare module '@blinkmobile/bm-identity/lib/login-providers/username.js' {
  declare module.exports: $Exports<'@blinkmobile/bm-identity/lib/login-providers/username'>;
}
declare module '@blinkmobile/bm-identity/lib/utils/get-access-token.js' {
  declare module.exports: $Exports<'@blinkmobile/bm-identity/lib/utils/get-access-token'>;
}
declare module '@blinkmobile/bm-identity/lib/utils/get-jwt.js' {
  declare module.exports: $Exports<'@blinkmobile/bm-identity/lib/utils/get-jwt'>;
}
declare module '@blinkmobile/bm-identity/lib/utils/get-refresh-token.js' {
  declare module.exports: $Exports<'@blinkmobile/bm-identity/lib/utils/get-refresh-token'>;
}
declare module '@blinkmobile/bm-identity/lib/utils/get-tenant-data.js' {
  declare module.exports: $Exports<'@blinkmobile/bm-identity/lib/utils/get-tenant-data'>;
}
declare module '@blinkmobile/bm-identity/lib/utils/user-config.js' {
  declare module.exports: $Exports<'@blinkmobile/bm-identity/lib/utils/user-config'>;
}
declare module '@blinkmobile/bm-identity/lib/utils/verify-jwt.js' {
  declare module.exports: $Exports<'@blinkmobile/bm-identity/lib/utils/verify-jwt'>;
}
declare module '@blinkmobile/bm-identity/test/common/login.js' {
  declare module.exports: $Exports<'@blinkmobile/bm-identity/test/common/login'>;
}
declare module '@blinkmobile/bm-identity/test/common/logout.js' {
  declare module.exports: $Exports<'@blinkmobile/bm-identity/test/common/logout'>;
}
declare module '@blinkmobile/bm-identity/test/helpers/base-64-url.js' {
  declare module.exports: $Exports<'@blinkmobile/bm-identity/test/helpers/base-64-url'>;
}
declare module '@blinkmobile/bm-identity/test/helpers/inquirer.js' {
  declare module.exports: $Exports<'@blinkmobile/bm-identity/test/helpers/inquirer'>;
}
declare module '@blinkmobile/bm-identity/test/helpers/jsonwebtoken.js' {
  declare module.exports: $Exports<'@blinkmobile/bm-identity/test/helpers/jsonwebtoken'>;
}
declare module '@blinkmobile/bm-identity/test/helpers/login-provider-base.js' {
  declare module.exports: $Exports<'@blinkmobile/bm-identity/test/helpers/login-provider-base'>;
}
declare module '@blinkmobile/bm-identity/test/helpers/login-provider.js' {
  declare module.exports: $Exports<'@blinkmobile/bm-identity/test/helpers/login-provider'>;
}
declare module '@blinkmobile/bm-identity/test/helpers/profile.js' {
  declare module.exports: $Exports<'@blinkmobile/bm-identity/test/helpers/profile'>;
}
declare module '@blinkmobile/bm-identity/test/helpers/request.js' {
  declare module.exports: $Exports<'@blinkmobile/bm-identity/test/helpers/request'>;
}
declare module '@blinkmobile/bm-identity/test/helpers/user-config.js' {
  declare module.exports: $Exports<'@blinkmobile/bm-identity/test/helpers/user-config'>;
}
declare module '@blinkmobile/bm-identity/test/login-providers/browser.js' {
  declare module.exports: $Exports<'@blinkmobile/bm-identity/test/login-providers/browser'>;
}
declare module '@blinkmobile/bm-identity/test/login-providers/login-provider-base.js' {
  declare module.exports: $Exports<'@blinkmobile/bm-identity/test/login-providers/login-provider-base'>;
}
declare module '@blinkmobile/bm-identity/test/login-providers/username.js' {
  declare module.exports: $Exports<'@blinkmobile/bm-identity/test/login-providers/username'>;
}
declare module '@blinkmobile/bm-identity/test/utils/verify-jwt.js' {
  declare module.exports: $Exports<'@blinkmobile/bm-identity/test/utils/verify-jwt'>;
}
